name: rss_feed_parser
description: A dart package for parsing and generating RSS1.0, RSS2.0, and Atom feeds.
version: 1.0.8
homepage: https://github.com/arhamcode/rss_feed_parser
repository: https://github.com/arhamcode/rss_feed_parser

environment:
  sdk: ^3.4.0

dependencies:
  http: ^1.2.1
  intl: ^0.19.0
  xml: ^6.5.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
